-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 19:54:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proginter_2022_a
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proginter_2022_a` ;

-- -----------------------------------------------------
-- Schema proginter_2022_a
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proginter_2022_a` DEFAULT CHARACTER SET utf8 ;
USE `proginter_2022_a` ;

-- -----------------------------------------------------
-- Table `proginter_2022_a`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proginter_2022_a`.`cliente` ;

CREATE TABLE IF NOT EXISTS `proginter_2022_a`.`cliente` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `logradouro` VARCHAR(60) NOT NULL,
  `numero` DECIMAL(5,0) NOT NULL,
  `complemento` VARCHAR(60) NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `referencia` VARCHAR(60) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`cliente_id`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proginter_2022_a`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proginter_2022_a`.`pedido` ;

CREATE TABLE IF NOT EXISTS `proginter_2022_a`.`pedido` (
  `pedido_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`pedido_id`),
  INDEX `fk_pedido_cliente_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `proginter_2022_a`.`cliente` (`cliente_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proginter_2022_a`.`pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proginter_2022_a`.`pizza` ;

CREATE TABLE IF NOT EXISTS `proginter_2022_a`.`pizza` (
  `pizza_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `descricao` VARCHAR(30) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`pizza_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proginter_2022_a`.`pedido_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proginter_2022_a`.`pedido_item` ;

CREATE TABLE IF NOT EXISTS `proginter_2022_a`.`pedido_item` (
  `pedido_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  `quantidade` DECIMAL(2,0) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `updated_at` TIMESTAMP NOT NULL DEFAULT current_timestamp on update current_timestamp,
  PRIMARY KEY (`pedido_id`, `pizza_id`),
  INDEX `fk_pedido_has_pizza_pizza1_idx` (`pizza_id` ASC) VISIBLE,
  INDEX `fk_pedido_has_pizza_pedido1_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_item01`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `proginter_2022_a`.`pedido` (`pedido_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_item02`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `proginter_2022_a`.`pizza` (`pizza_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- dados dos clientes
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(68) 3740-4790','Letícia Jaqueline Eloá Jesus','Rua Brasiléia','217','Calafate','Rio Branco','AC');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(93) 3914-8516','Manuel Thiago Galvão','Rua Dois','953','Liberdade','Altamira','PA');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(75) 3716-8362','Isabelle Melissa Allana Vieira','Rua Naiane Conrado','404','CIS','Feira de Santana','BA');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(96) 2984-2489','Bianca Márcia Farias','Rua Capitão Euclides Rodrigues','823','Provedor','Santana','AP');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(83) 3652-0340','Bryan Roberto Rocha','Praça João Pessoa','384','Centro','Santa Rita','PB');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(82) 2653-9459','Nathan Igor Baptista','Rua Maria Morena Gomes','143','Brasília','Arapiraca','AL');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(42) 3855-8190','Luís Pietro Thales da Rosa','Rua Radialista Nelson Annuziato','900','Boa Vista','Ponta Grossa','PR');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(91) 3619-9852','Fátima Pietra Giovanna Novaes','Travessa Dom Romualdo Coelho','501','Umarizal','Belém','PA');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(65) 3601-7621','Erick Sebastião André Drumond','Rua Palermo','122','Jardim Itália','Cuiabá','MT');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(34) 3877-6758','Manuel Thiago da Cunha','Rua Zama Alves','495','Lagoinha','Patos de Minas','MG');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(85) 3896-0645','Tiago Thales Murilo Carvalho','Rua 13','997','Jarí','Maracanaú','CE');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(86) 2624-3655','Igor Leandro Silveira','Rua Quatorze','748','Boa Vista','Timon','MA');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(98) 3981-6452','Antonella Clara Gomes','1ª Travessa Santa Luzia','416','Vila Ariri','São Luís','MA');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(66) 3920-1912','Raimundo Benício Renato Brito','Rua da Pirarara','772','Condomínio Residencial Camping Club','Sinop','MT');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(27) 2677-5725','Hadassa Luana Eliane Cardoso','Rua A','256','Campo Verde','Viana','ES');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(54) 3943-3684','Milena Louise Costa','Rua Fernando Francisco Kaller','118','São Leopoldo','Caxias do Sul','RS');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(92) 2969-6757','Marcelo Carlos Monteiro','Rua Machado de Assis','134','Tiradentes','Itacoatiara','AM');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(66) 2669-4895','Vitória Ana Alice Assunção','Rua Projetada 10','944','Residencial Sabrina II','Sinop','MT');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(31) 2570-8648','Isaac Gustavo dos Santos','Rua Dona Eugênia Teixeira Bráulio','467','Sagrado Coração de Jesus','Ponte Nova','MG');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(67) 3613-6025','Mariane Sophia da Cruz','Rua Guilherme de Almeida','160','Nova Lima','Campo Grande','MS');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(82) 3930-9516','Roberto Geraldo Mário Teixeira','Rua Projetada D-2','130','Jacarecica','Maceió','AL');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(85) 2567-0779','Rosângela Bruna Pereira','Rua Joaquim Trajano','756','Pedras','Fortaleza','CE');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(85) 2958-4507','Antonella Carla Sebastiana Sales','Rua Amaro Abreu','698','Itapoã','Caucaia','CE');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(31) 3789-6950','Mariane Sophia Souza','Rua das Cítaras','647','Conjunto Califórnia','Belo Horizonte','MG');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(91) 2751-1747','Igor Daniel Cauã Dias','Alameda Natal','170','Curuçambá','Ananindeua','PA');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(95) 3569-7235','Ester Isabelly Isabelle Almeida','Travessa A','153','Centro','Boa Vista','RR');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(83) 2629-9726','Renata Yasmin Rosa Rezende','Rua Porto do Capim','411','Varadouro','João Pessoa','PB');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(86) 2917-1336','Sara Milena Luna Aragão','Rua Arlindo Nogueira','480','Mafuá','Teresina','PI');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(96) 3627-1191','Mariah Malu Allana Silva','Avenida Costa e Silva, s/n','363','Centro','Ferreira Gomes','AP');
insert into cliente(telefone,nome,logradouro,numero,bairro,cidade,uf) values ('(21) 2517-1824','Sabrina Stefany Araújo','Rua Comendador Siqueira','919','Pechincha','Rio de Janeiro','RJ');
-- Pizzas
insert into pizza(nome,descricao,valor) values('Portuguesa','Portuguesa',15);
insert into pizza(nome,descricao,valor) values('Provolone','Provolone',17);
insert into pizza(nome,descricao,valor) values('4 Queijos','4 Queijos',20);
insert into pizza(nome,descricao,valor) values('Calabresa','Calabresa',17);
insert into pizza(nome,descricao,valor) values('Escarola','Escarola',22);
-- Pedidos
insert into pedido(cliente_id,data,valor) values(30,'2022-04-10',0);
insert into pedido(cliente_id,data,valor) values(22,'2022-02-14',0);
insert into pedido(cliente_id,data,valor) values(9,'2022-04-09',0);
insert into pedido(cliente_id,data,valor) values(17,'2022-09-10',0);
insert into pedido(cliente_id,data,valor) values(10,'2022-08-20',0);
insert into pedido(cliente_id,data,valor) values(14,'2022-10-17',0);
insert into pedido(cliente_id,data,valor) values(3,'2022-07-20',0);
insert into pedido(cliente_id,data,valor) values(22,'2022-06-04',0);
insert into pedido(cliente_id,data,valor) values(9,'2022-05-23',0);
insert into pedido(cliente_id,data,valor) values(3,'2022-09-14',0);
insert into pedido(cliente_id,data,valor) values(23,'2022-06-13',0);
insert into pedido(cliente_id,data,valor) values(6,'2022-08-28',0);
insert into pedido(cliente_id,data,valor) values(25,'2022-02-01',0);
insert into pedido(cliente_id,data,valor) values(11,'2022-06-13',0);
insert into pedido(cliente_id,data,valor) values(19,'2022-10-11',0);
insert into pedido(cliente_id,data,valor) values(26,'2022-03-20',0);
insert into pedido(cliente_id,data,valor) values(4,'2022-03-31',0);
insert into pedido(cliente_id,data,valor) values(20,'2022-10-16',0);
insert into pedido(cliente_id,data,valor) values(26,'2022-03-22',0);
insert into pedido(cliente_id,data,valor) values(27,'2022-01-05',0);
insert into pedido(cliente_id,data,valor) values(29,'2022-09-07',0);
insert into pedido(cliente_id,data,valor) values(17,'2022-03-07',0);
insert into pedido(cliente_id,data,valor) values(7,'2022-05-15',0);
insert into pedido(cliente_id,data,valor) values(12,'2022-01-10',0);
insert into pedido(cliente_id,data,valor) values(24,'2022-06-01',0);
insert into pedido(cliente_id,data,valor) values(3,'2022-04-21',0);
insert into pedido(cliente_id,data,valor) values(27,'2022-07-10',0);
insert into pedido(cliente_id,data,valor) values(6,'2022-09-20',0);
insert into pedido(cliente_id,data,valor) values(30,'2022-02-15',0);
insert into pedido(cliente_id,data,valor) values(1,'2022-10-10',0);
insert into pedido(cliente_id,data,valor) values(7,'2022-04-17',0);
insert into pedido(cliente_id,data,valor) values(13,'2022-06-11',0);
insert into pedido(cliente_id,data,valor) values(17,'2022-06-12',0);
insert into pedido(cliente_id,data,valor) values(20,'2022-08-25',0);
insert into pedido(cliente_id,data,valor) values(18,'2022-02-28',0);
insert into pedido(cliente_id,data,valor) values(16,'2022-09-06',0);
insert into pedido(cliente_id,data,valor) values(14,'2022-07-17',0);
insert into pedido(cliente_id,data,valor) values(14,'2022-05-10',0);
insert into pedido(cliente_id,data,valor) values(21,'2022-09-26',0);
insert into pedido(cliente_id,data,valor) values(21,'2022-01-16',0);
insert into pedido(cliente_id,data,valor) values(29,'2022-01-08',0);
insert into pedido(cliente_id,data,valor) values(25,'2022-02-27',0);
insert into pedido(cliente_id,data,valor) values(11,'2022-07-28',0);
insert into pedido(cliente_id,data,valor) values(21,'2022-08-19',0);
insert into pedido(cliente_id,data,valor) values(7,'2022-07-10',0);
insert into pedido(cliente_id,data,valor) values(26,'2022-10-15',0);
insert into pedido(cliente_id,data,valor) values(20,'2022-10-28',0);
insert into pedido(cliente_id,data,valor) values(1,'2022-04-02',0);
insert into pedido(cliente_id,data,valor) values(30,'2022-10-19',0);
insert into pedido(cliente_id,data,valor) values(23,'2022-01-27',0);
insert into pedido(cliente_id,data,valor) values(13,'2022-05-15',0);
insert into pedido(cliente_id,data,valor) values(13,'2022-06-13',0);
insert into pedido(cliente_id,data,valor) values(14,'2022-04-09',0);
insert into pedido(cliente_id,data,valor) values(12,'2022-09-18',0);
insert into pedido(cliente_id,data,valor) values(20,'2022-03-18',0);
insert into pedido(cliente_id,data,valor) values(25,'2022-07-03',0);
insert into pedido(cliente_id,data,valor) values(15,'2022-04-27',0);
insert into pedido(cliente_id,data,valor) values(10,'2022-10-31',0);
insert into pedido(cliente_id,data,valor) values(26,'2022-05-03',0);
-- Pedidos itens
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (1,1,4,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (2,1,2,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (3,5,3,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (5,2,5,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (6,4,4,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (8,3,3,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (9,1,2,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (9,2,5,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (9,3,4,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (9,5,5,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (11,2,3,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (11,5,5,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (12,1,1,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (14,1,3,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (15,2,4,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (15,5,2,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (16,1,2,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (16,4,3,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (18,1,4,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (18,3,1,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (19,2,3,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (19,3,5,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (20,2,1,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (20,4,3,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (22,1,5,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (22,3,4,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (23,3,1,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (23,4,1,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (24,3,4,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (25,2,4,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (25,5,1,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (27,2,3,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (27,3,1,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (27,4,1,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (27,5,3,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (28,2,2,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (28,5,1,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (29,3,4,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (29,4,2,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (29,5,5,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (30,1,2,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (31,4,1,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (32,1,4,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (32,2,2,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (32,3,5,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (32,4,3,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (34,4,5,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (34,5,1,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (35,3,3,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (36,1,3,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (36,2,4,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (36,3,2,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (36,4,2,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (36,5,1,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (37,5,2,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (38,2,2,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (38,4,4,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (39,1,4,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (40,1,3,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (40,2,4,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (40,4,5,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (40,3,4,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (41,2,5,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (41,3,5,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (42,1,3,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (42,2,3,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (42,4,1,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (43,3,3,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (44,2,5,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (44,3,4,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (45,3,1,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (45,5,1,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (46,3,2,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (46,2,3,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (46,4,2,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (47,2,1,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (49,5,3,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (49,4,1,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (50,3,5,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (50,5,2,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (51,3,3,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (52,4,4,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (55,4,2,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (57,2,3,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (57,5,5,22);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (58,1,3,15);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (58,2,4,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (58,4,2,17);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (58,3,4,20);
insert into pedido_item(pedido_id,pizza_id,quantidade,valor) values (58,5,2,22);
