use proginter_2022_a;
CREATE TABLE `users` (
	`email` VARCHAR(120) NOT NULL,
	`nome` VARCHAR(45) NOT NULL,
	`senha` VARCHAR(80) NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`email`)
);
